"""add draft status

Revision ID: 5c19ff373cde
Revises: c477f4bef0f0
Create Date: 2026-06-20 12:14:12.509107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c19ff373cde'
down_revision: Union[str, Sequence[str], None] = 'c477f4bef0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE documentstatus ADD VALUE 'DRAFT';"
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
