"""add document status enum

Revision ID: c477f4bef0f0
Revises: 9d0c68a07cff
Create Date: 2026-06-13 20:06:23.112246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c477f4bef0f0'
down_revision: Union[str, Sequence[str], None] = '9d0c68a07cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    document_status = sa.Enum(
        'PROCESSING',
        'READY',
        'FAILED',
        name='documentstatus'
    )

    document_status.create(
        op.get_bind(),
        checkfirst=True
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'documents',
        'status',
        existing_type=sa.VARCHAR(),
        type_=document_status,
        existing_nullable=False,
        postgresql_using='status::documentstatus'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'documents',
        'status',
        existing_type=sa.Enum(
            'PROCESSING',
            'READY',
            'FAILED',
            name='documentstatus'
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False
    )

    sa.Enum(
        'PROCESSING',
        'READY',
        'FAILED',
        name='documentstatus'
    ).drop(
        op.get_bind(),
        checkfirst=True
    )
    # ### end Alembic commands ###
